name: Untrusted Script Evaluation

on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: "example.com/owner/image"
      credentials:
        username: hardcoded-username
        password: hardcoded-password

    services:
      redis:
        image: redis
        credentials:
          username: hardcoded-username
          password: hardcoded-password

    steps:
      - run: echo "Hello World!"
